apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "grpc1"
  description: "desc.backstage"
  annotations:
    github.com/project-slug: t1ynx/https://github.com/t1ynx
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://admin.example-org.com
      title: Jira Project
      icon: dashboard
  tags:
    - tag1
    - tag2
    - tag3
spec:
  type: service
  lifecycle: experimental
  owner: "team-cit"
  targets:
    - ./team-cit.yaml
