apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "grpc"
  description: "desc.backstage"
  annotations:
    github.com/project-slug: t1ynx/https://github.com/t1ynx
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
